### ISSUE TITLE
Stuck on contract

### ISSUE THREAD

**Issue by Moeshrande** [buildship-dev/nft-contracts#32]
Hi there, If I want to set this up for a donation process, what kind of contract do I need? I want a pre-stated amount of eth for a donation, lets say 0.005 ETH, and let the people choose if they want to donate it 1 time, 2 times or 3 times (so the current application is perfect).

Some help would be awesome, thanks a lot!!

**Comment by caffeinum** [comment]
@Moeshrande you can just use `MetaverseNFT` as a donation receipt
