### ISSUE TITLE
erc721a startTokenId is not initialized when constructor is called

### ISSUE THREAD

**Issue by caffeinum** [buildship-dev/nft-contracts#63]
https://github.com/buildship-dev/nft-contracts/blob/8347b5ee9d218815479e7676deab708c9ed5e941/contracts/MetaverseBaseNFT.sol#L125

**Comment by theshadowagent** [comment]
https://github.com/chiru-labs/ERC721A/blob/002562b50e052ce8bf1a611edb9bec1ca495eba3/contracts/ERC721A.sol#L154
