### ISSUE TITLE
Floating Pragmas

### ISSUE THREAD

**Issue by DevABDee** [buildship-dev/nft-contracts#71]
Not a problem, but a lousy solidity's code practice, Every contract has a floating `pragma` which is not recommended. It should be fixed.

Fix the Pragmas

Additional context:
Check this: https://t.co/PsMruMmE6t

Thanks,
AB Dee

**Comment by DevABDee** [comment]
Pragma Fixed #72

**Comment by caffeinum** [comment]
Thanks for your contribution!

For `ERC721CommunityBase`, I don't want to force users to fix their compiler version. Some of these contracts might be used in other projects that have their own compiler version
