### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by Hironate** [buildship-dev/nft-contracts#73]
Contract have centralization danger, developer can withdraw all money which is raised by minting NFT deployed using buildShip. This is no good.

**Comment by theshadowagent** [comment]
The function in question just force triggers the same withdraw function that is called by the creator. There is no danger if the creator has the correct payout address. 
Can you explain why this is bad specifically?

**Comment by Hironate** [comment]
Really sorry, my bad. Opened issue without going much into details. Feel free to close it.
